### ISSUE TITLE
Add backlinks functionality

### ISSUE THREAD

**Issue by carbontwelve** [photogabble/website#93]
- https://github.com/11ty/eleventy/issues/1407
- From the above issue [This 11ty Digital Garden theme](https://github.com/binyamin/eleventy-garden) was linked. It contains backlinks functionality in its [`notes.11tydata.js`](https://github.com/binyamin/eleventy-garden/blob/main/notes/notes.11tydata.js) and within an inline  markdown-it plugin within its [`.eleventy.js`](https://github.com/binyamin/eleventy-garden/blob/main/.eleventy.js#L12-L23) file.
- I think the aforementioned is where [Evan](https://boehs.org/) got his functionality from as shown in his [`garden.11tydata.js`](https://git.sr.ht/~boehs/site/tree/master/item/html/pages/garden/garden.11tydata.js)

**Comment by carbontwelve** [comment]
@binyamin that certainly looks interesting. 

Unlike other gardens where their interlinked notes are under a single permalink e.g `/domain.com/notes` my content types have their own base permalink e.g https://photogabble.co.uk/essays/ and https://photogabble.co.uk/noteworthy/ these all originate from https://github.com/photogabble/website/tree/main/content.

**Comment by binyamin** [comment]
@carbontwelve I could modify it. Do you need multiple, separate base folders? Or just a single base folder?
